# version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_database
    restart: unless-stopped
    ports:
      - "27017:27017"
    env_file:
      - ./env/db_env/db.env
    volumes:
      - ./mongo-data:/data/db
